name: Test and publish

on:
  push:
  pull_request:

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: 17
          registry-url: https://registry.npmjs.org/
      - name: Install dependencies
        run: npm ci
      - name: Build
        run: npm run build
      - name: Publish package to npm
        uses: JS-DevTools/npm-publish@v1
        if: github.ref == 'refs/heads/master' && github.event_name == 'push'
        with:
          token: ${{ secrets.NPM_TOKEN }}
          access: public
